export const TABLE__RESIZE = 'TABLE_RESIZE'
export const CHANGE__TEXT = 'CHANGE__TEXT'
export const APPLY_STYLE = 'APPLY_STYLE'
export const CHANGE_STYLES = 'CHANGE_STYLES'
export const CHANGE__TITLE = 'CHANGE__TITLE'